# ai/app/agents/orchestrator.py
from google.adk import Agent, Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types
from app.services.llm_service import LLMService
from app.models.enums import AgentRole
from app.schemas.orchestrator import OrchestratorResponse

class OrchestratorAgent:
    """
    The primary routing agent for Marka AI.
    Uses Gemini 3 Flash to parse intent via structured CoT.
    """
    def __init__(self):
        self.llm_service = LLMService()
        self.session_service = InMemorySessionService()
        
        # Configure the ADK Agent
        self.agent = Agent(
            name="Orchestrator",
            model=self.llm_service.get_adk_model(AgentRole.ORCHESTRATOR),
            instruction=(
                "You are the Marka AI Orchestrator. Your job is to route user messages to the correct sub-agent.\n"
                "Analyze the user's message in English in the 'thought_process' field first.\n"
                "Then, pick the correct 'intent' from the AgentRole list.\n"
                "Available intents:\n"
                "- 'chatbot': Greetings, help, or casual chat.\n"
                "- 'content': Requests to create posts, captions, or marketing content.\n"
                "- 'rag': Specific questions about products or brand information.\n"
                "If ambiguous, default to 'chatbot' and ask for more details."
            ),
            # Force structured output using our schema
            output_schema=OrchestratorResponse
        )

    async def parse_intent(self, user_text: str) -> OrchestratorResponse:
        """Invokes the agent and returns the structured response."""
        async with Runner(
            app_name="MarkaAI",
            agent=self.agent,
            session_service=self.session_service,
            auto_create_session=True
        ) as runner:
            
            message = types.Content(
                role="user", 
                parts=[types.Part.from_text(text=user_text)]
            )
            
            # We take the first complete response from the generator
            async for event in runner.run_async(
                user_id="internal_tester",
                session_id="orchestrator_parse",
                new_message=message
            ):
                # When output_schema is provided, ADK returns a text part with JSON
                if hasattr(event, 'content') and event.content.parts:
                    raw_text = event.content.parts[0].text
                    # Use Pydantic's built-in JSON parsing to return the validated object
                    return OrchestratorResponse.model_validate_json(raw_text)
            
            raise ValueError("No response generated by Orchestrator")
