# ai/app/agents/content/agent.py
from typing import Optional, Any

from google.adk import Agent, Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from app.services.llm_service import LLMService
from app.models.enums import AgentRole, EmailStrategy
from app.schemas.content import ContentResponse


class ContentAgent:
    """Specialized content generation agent for Marka AI.

    Produces marketing emails in Egyptian Arabic dialect tailored for
    small and medium enterprises (SMEs). Uses Chain-of-Thought reasoning
    to analyze the product and strategy before generating structured
    email content with subject lines, body parts, and optional
    sender/recipient personalization.
    """

    def __init__(self, settings: Optional[Any] = None) -> None:
        """Initializes the Content agent with dependencies and configuration.

        Args:
            settings: Configuration settings for dependency injection.
                     Passed to LLMService to configure the model.
        """
        self.llm_service = LLMService(settings=settings)
        self.session_service = InMemorySessionService()

        self.agent = Agent(
            name="Content",
            model=self.llm_service.get_adk_model(AgentRole.CONTENT),
            instruction=(
                "You are the Marka AI Content Agent. Your job is to generate "
                "marketing emails for small and medium enterprises (SMEs).\n"
                "1. Read the product description and email strategy provided.\n"
                "2. Think step by step in English about the product's key selling "
                "points, target audience, and appropriate email tone. Write this "
                "reasoning in the 'thought_process' field.\n"
                "3. Generate marketing emails in Egyptian Arabic dialect "
                "(colloquial Egyptian). Each email must include:\n"
                "   - A catchy subject line\n"
                "   - A strategy type (promotional, newsletter, welcome, etc.)\n"
                "   - Ordered parts: at least header, body, and call_to_action\n"
                "   - Optional sender and recipient fields if relevant\n"
                "4. Return the result using the structured output schema."
            ),
            output_schema=ContentResponse,
        )

    async def generate_email(
        self,
        product_description: str,
        strategy: EmailStrategy = EmailStrategy.PROMOTIONAL,
    ) -> ContentResponse:
        """Generates marketing emails for the given product and strategy.

        Args:
            product_description: A description of the product or service
                                to create marketing content for.
            strategy: The email campaign strategy type (promotional,
                     newsletter, welcome, etc.).

        Returns:
            ContentResponse: The validated response containing thought_process
                            and a list of MarketingEmail objects.

        Raises:
            ValueError: If the Content agent fails to produce a valid response
                       or if the JSON parsing of the structured output fails.
        """
        async with Runner(
            app_name="MarkaAI",
            agent=self.agent,
            session_service=self.session_service,
            auto_create_session=True,
        ) as runner:
            prompt = f"Product: {product_description}\nEmail Strategy: {strategy.value}"
            message = types.Content(
                role="user",
                parts=[types.Part.from_text(text=prompt)],
            )

            async for event in runner.run_async(
                user_id="internal_tester",
                session_id="content_generate",
                new_message=message,
            ):
                if hasattr(event, "content") and event.content.parts:
                    raw_text = event.content.parts[0].text
                    if not raw_text:
                        continue

                    try:
                        return ContentResponse.model_validate_json(raw_text)
                    except Exception as e:
                        raise ValueError(
                            f"Content agent returned invalid JSON format: {str(e)}"
                        ) from e

            raise ValueError(
                "No valid structured response was generated by the Content agent."
            )
