# ai/app/agents/content/agent.py
from typing import Optional, Any

from google.adk import Agent, Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from app.services.llm_service import LLMService
from app.models.enums import AgentRole
from app.schemas.content import ContentResponse


class ContentAgent:
    """
    Specialized content generation agent for Marka AI.

    This agent produces marketing captions in Egyptian Arabic dialect
    tailored for small and medium enterprises (SMEs). It uses Chain-of-Thought
    reasoning to analyze the product description before generating exactly
    3 engaging social media captions.
    """

    def __init__(self, settings: Optional[Any] = None) -> None:
        """
        Initializes the Content agent with dependencies and configuration.

        Args:
            settings: Configuration settings for dependency injection.
                     Passed to LLMService to configure the model.
        """
        self.llm_service = LLMService(settings=settings)
        self.session_service = InMemorySessionService()

        self.agent = Agent(
            name="Content",
            model=self.llm_service.get_adk_model(AgentRole.CONTENT),
            instruction=(
                "You are the Marka AI Content Agent. Your job is to generate "
                "marketing captions for small and medium enterprises (SMEs).\n"
                "1. Read the product description provided by the user.\n"
                "2. Think step by step in English about the product's key selling "
                "points, target audience, and tone of voice. Write this reasoning "
                "in the 'thought_process' field.\n"
                "3. Generate exactly 3 marketing captions in Egyptian Arabic "
                "dialect (colloquial Egyptian). Each caption should be engaging, "
                "concise, and suitable for social media (Facebook, Instagram).\n"
                "4. Return the result using the structured output schema."
            ),
            output_schema=ContentResponse,
        )

    async def generate_captions(self, product_description: str) -> ContentResponse:
        """
        Generates marketing captions for the given product description.

        Args:
            product_description: A description of the product or service
                                to create marketing content for.

        Returns:
            ContentResponse: The validated response containing thought_process
                            and a list of 3 Egyptian Arabic captions.

        Raises:
            ValueError: If the Content agent fails to produce a valid response
                       or if the JSON parsing of the structured output fails.
        """
        async with Runner(
            app_name="MarkaAI",
            agent=self.agent,
            session_service=self.session_service,
            auto_create_session=True,
        ) as runner:
            message = types.Content(
                role="user",
                parts=[types.Part.from_text(text=product_description)],
            )

            async for event in runner.run_async(
                user_id="internal_tester",
                session_id="content_generate",
                new_message=message,
            ):
                if hasattr(event, "content") and event.content.parts:
                    raw_text = event.content.parts[0].text
                    if not raw_text:
                        continue

                    try:
                        return ContentResponse.model_validate_json(raw_text)
                    except Exception as e:
                        raise ValueError(
                            f"Content agent returned invalid JSON format: {str(e)}"
                        ) from e

            raise ValueError(
                "No valid structured response was generated by the Content agent."
            )
